# Generated by Django 2.2 on 2020-11-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_desc_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desc',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses_app.desc'),
        ),
    ]
