# Generated by Django 2.2 on 2020-11-03 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_auto_20201103_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='desc',
            name='id',
        ),
        migrations.AddField(
            model_name='desc',
            name='course',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='desc', serialize=False, to='courses_app.course'),
            preserve_default=False,
        ),
    ]
